test_that("detectOrganism",  {
    human <- detectOrganism("Homo sapiens")
    expect_identical(human, c(human = "Homo sapiens"))
    expect_equal(human, detectOrganism("hsapiens"))
    expect_equal(human, detectOrganism("human"))
    expect_equal(human, detectOrganism("GRCh38"))
    expect_equal(human, detectOrganism("grch38"))
    expect_equal(human, detectOrganism("hg38"))
    expect_equal(human, detectOrganism("ENSG00000000001"))
    expect_equal(human, detectOrganism("ENST00000000001"))

    mouse <- detectOrganism("mouse")
    expect_identical(mouse, c(mouse = "Mus musculus"))
    expect_equal(mouse, detectOrganism("mmusculus"))
    expect_equal(mouse, detectOrganism("mouse"))
    expect_equal(mouse, detectOrganism("GRCm38"))
    expect_equal(mouse, detectOrganism("grcm38"))
    expect_equal(mouse, detectOrganism("mm10"))
    expect_equal(mouse, detectOrganism("ENSMUSG00000000001"))
    expect_equal(mouse, detectOrganism("ENSMUST00000000001"))

    fruitfly <- detectOrganism("fruitfly")
    expect_identical(fruitfly, c(fruitfly = "Drosophila melanogaster"))
    expect_equal(fruitfly, detectOrganism("dmelanogaster"))
    expect_equal(fruitfly, detectOrganism("fruitfly"))
    expect_equal(fruitfly, detectOrganism("BDGP6"))
    expect_equal(fruitfly, detectOrganism("dm6"))
    expect_equal(fruitfly, detectOrganism("FBgn0000001"))
    expect_equal(fruitfly, detectOrganism("FBtr0000001"))

    roundworm <- detectOrganism("roundworm")
    expect_identical(roundworm, c(roundworm = "Caenorhabditis elegans"))
    expect_equal(roundworm, detectOrganism("celegans"))
    expect_equal(roundworm, detectOrganism("roundworm"))
    expect_equal(roundworm, detectOrganism("WBcel235"))
    expect_equal(roundworm, detectOrganism("ce11"))
    expect_equal(roundworm, detectOrganism("WBGene00000001"))

    chicken <- detectOrganism("chicken")
    expect_identical(chicken, c(chicken = "Gallus gallus"))
    expect_equal(chicken, detectOrganism("ggallus"))
    expect_equal(chicken, detectOrganism("chicken"))
    expect_equal(chicken, detectOrganism("ENSGALG00000000001"))
    expect_equal(chicken, detectOrganism("ENSGALT00000000001"))

    rat <- detectOrganism("rat")
    expect_identical(rat, c(rat = "Rattus norvegicus"))
    expect_equal(rat, detectOrganism("rnorvegicus"))
    expect_equal(rat, detectOrganism("rat"))
    expect_equal(rat, detectOrganism("ENSRNOG00000000001"))
    expect_equal(rat, detectOrganism("ENSRNOT00000000001"))
})
